---
- name: Create users
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
  loop: "{{ users }}"

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"
  when: item.ssh_key is defined

- name: Add SSH key to authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
  loop: "{{ users }}"
  when: item.ssh_key is defined

- name: Grant sudo privileges if specified
  copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'
  loop: "{{ users }}"
  when: item.sudo | default(false) | bool
